### ISSUE TITLE
Should the binary be called libyear-rb or libyear-bundler?

### ISSUE THREAD

**Issue by sbleon** [jaredbeck/libyear-rb#1]
I noticed that the npm version's binary is `libyear-npm`. Maybe this version should have a more specific binary name too?

This could leave the `libyear` binary name available for a future project that knew how to run all of the various specific `libyear-*`s and aggregate them :-)

**Comment by jaredbeck** [comment]
Makes sense. I'll look into changing it.

**Comment by jaredbeck** [comment]
Closed by release 0.2.0. Going forward please use libyear-bundler. 

> This could leave the libyear binary name available for a future project that knew how to run all of the various specific libyear-*s and aggregate them :-)

It's a great idea, let's do it.
